### ISSUE TITLE
Migrate Biocultural Heritage site

### ISSUE THREAD

**Issue by cbrody** [IIED-org/iiedmulti#26]
https://biocultural.iied.org
https://prod.biocultural.iied.org

- [x] Test prod site
- [x] Migrate code & config
- [x] Content freeze - readonlymode?
- [x] Migrate db & files
- [x] Test
- [x] Update DNS etc.
- [x] Test

Launch target: 20241022T14:00

**Comment by stephen-cox** [comment]
@cbrody This site now setup on the new server and ready to test: https://prod.biocultural.iied.org/
